sql:
    default: 'postgre'
    postgre:
        lib: 'psycopg2'
        args: []
        kwargs:
            host: "fhir-pipe-mimic-db"
            port: 5432
            database: "mimic"
            user: "mimicuser"
            password: "mimicuser"
    fhirbase:
        lib: 'psycopg2'
        args: []
        kwargs:
            host: "fhir-pipe-fhirbase"
            port: 5432
            database: "fhirbase"
            user: "postgres"
            password: "postgres"
    oracle:
        lib: 'cx_Oracle'
        args: ['user/password@database']
        kwargs: {}

graphql:
    server: 'https://graphql.pyrog.staging.arkhn.org/'
    token: "<token>"
